services:
  bot:
    image: ghrc.io/emberlyte/water-bot:latest
    build: .
    container_name: waterbot
    restart: unless-stopped
    volumes:
      - sqlite_data:/app/data
    env_file:
      - .env

volumes:
  sqlite_data:
